// <auto-generated />
using System;
using System.Text.Json;
using DigitalOps.API.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DigitalOps.API.Shared.Data.Migrations
{
    [DbContext(typeof(DigitalOpsDbContext))]
    [Migration("20260803150752_AddLegalRagGovernance")]
    partial class AddLegalRagGovernance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DigitalOps.API.Features.Attachments.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ExtractedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("extracted_at");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text")
                        .HasColumnName("extracted_text");

                    b.Property<string>("ExtractionError")
                        .HasColumnType("text")
                        .HasColumnName("extraction_error");

                    b.Property<string>("ExtractionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("extraction_status");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<Guid?>("IncomingDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incoming_document_id");

                    b.Property<Guid?>("OutgoingDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("outgoing_document_id");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("file_url");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UploadedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_staff_id");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("ExtractionStatus")
                        .HasDatabaseName("ix_attachments_extraction_status");

                    b.HasIndex("IncomingDocumentId")
                        .HasDatabaseName("ix_attachments_incoming_document_id");

                    b.HasIndex("OutgoingDocumentId")
                        .HasDatabaseName("ix_attachments_outgoing_document_id");

                    b.HasIndex("UploadedByStaffId")
                        .HasDatabaseName("ix_attachments_uploaded_by_staff_id");

                    b.ToTable("attachments", null, t =>
                        {
                            t.HasCheckConstraint("ck_attachments_exactly_one_parent", "num_nonnulls(incoming_document_id, outgoing_document_id) = 1");

                            t.HasCheckConstraint("ck_attachments_extraction_status", "extraction_status IN ('Pending', 'Processing', 'Succeeded', 'Failed', 'Unsupported')");

                            t.HasCheckConstraint("ck_attachments_failed_error", "extraction_status <> 'Failed' OR (extraction_error IS NOT NULL AND length(trim(extraction_error)) > 0)");

                            t.HasCheckConstraint("ck_attachments_succeeded_extracted_at", "extraction_status <> 'Succeeded' OR extracted_at IS NOT NULL");
                        });
                });

            modelBuilder.Entity("DigitalOps.API.Features.Drafting.DocumentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_type_id");

                    b.Property<JsonElement>("FormatRules")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("format_rules")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TemplateContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_content");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_document_templates");

                    b.HasIndex("DocumentTypeId")
                        .HasDatabaseName("ix_document_templates_document_type_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_document_templates_is_active");

                    b.HasIndex("DocumentTypeId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_document_templates_type_name");

                    b.ToTable("document_templates", null, t =>
                        {
                            t.HasCheckConstraint("ck_document_templates_format_rules_object", "jsonb_typeof(format_rules) = 'object'");
                        });
                });

            modelBuilder.Entity("DigitalOps.API.Features.Drafting.DocumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_document_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_document_types_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_document_types_is_active");

                    b.ToTable("document_types", (string)null);
                });

            modelBuilder.Entity("DigitalOps.API.Features.IncomingDocuments.IncomingDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AssignedToStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_staff_id");

                    b.Property<decimal?>("AssignmentConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("assignment_confidence");

                    b.Property<DateTime?>("AssignmentConfirmedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("assignment_confirmed_at");

                    b.Property<Guid?>("AssignmentConfirmedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_confirmed_by_staff_id");

                    b.Property<DateTime?>("AssignmentSuggestedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("assignment_suggested_at");

                    b.Property<string>("AssignmentSuggestionReason")
                        .HasColumnType("text")
                        .HasColumnName("assignment_suggestion_reason");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_type_id");

                    b.Property<DateOnly>("ReceivedDate")
                        .HasColumnType("date")
                        .HasColumnName("received_date");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_number");

                    b.Property<string>("SenderOrg")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sender_org");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("New")
                        .HasColumnName("status");

                    b.Property<Guid?>("SuggestedStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggested_staff_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_incoming_documents");

                    b.HasIndex("AssignmentConfirmedByStaffId")
                        .HasDatabaseName("ix_incoming_documents_confirmed_by_staff_id");

                    b.HasIndex("DocumentTypeId")
                        .HasDatabaseName("ix_incoming_documents_document_type_id");

                    b.HasIndex("SuggestedStaffId")
                        .HasDatabaseName("ix_incoming_documents_suggested_staff_id");

                    b.HasIndex("AssignedToStaffId", "Status")
                        .HasDatabaseName("ix_incoming_documents_assigned_status");

                    b.HasIndex("ReferenceNumber", "SenderOrg")
                        .HasDatabaseName("ix_incoming_documents_reference_sender");

                    b.HasIndex("Status", "Deadline")
                        .HasDatabaseName("ix_incoming_documents_status_deadline");

                    b.ToTable("incoming_documents", null, t =>
                        {
                            t.HasCheckConstraint("ck_incoming_documents_assignment_confidence", "assignment_confidence IS NULL OR (assignment_confidence >= 0 AND assignment_confidence <= 1)");

                            t.HasCheckConstraint("ck_incoming_documents_assignment_tuple", "(assigned_to_staff_id IS NULL AND assignment_confirmed_by_staff_id IS NULL AND assignment_confirmed_at IS NULL) OR (assigned_to_staff_id IS NOT NULL AND assignment_confirmed_by_staff_id IS NOT NULL AND assignment_confirmed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_incoming_documents_received_deadline", "received_date <= deadline");

                            t.HasCheckConstraint("ck_incoming_documents_status", "status IN ('New', 'InProgress', 'Completed', 'Overdue')");

                            t.HasCheckConstraint("ck_incoming_documents_status_completed_at", "(status = 'Completed' AND completed_at IS NOT NULL) OR (status <> 'Completed' AND completed_at IS NULL)");

                            t.HasCheckConstraint("ck_incoming_documents_suggestion_tuple", "(suggested_staff_id IS NULL AND assignment_suggestion_reason IS NULL AND assignment_confidence IS NULL AND assignment_suggested_at IS NULL) OR (suggested_staff_id IS NOT NULL AND assignment_suggested_at IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("DigitalOps.API.Features.Members.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<DateOnly?>("JoinDate")
                        .HasColumnType("date")
                        .HasColumnName("join_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("position");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_members_email");

                    b.HasIndex("FullName")
                        .HasDatabaseName("ix_members_full_name");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_members_phone");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_members_status");

                    b.ToTable("members", null, t =>
                        {
                            t.HasCheckConstraint("ck_members_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("DigitalOps.API.Features.OutgoingDocuments.OutgoingDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AiDraftContent")
                        .HasColumnType("text")
                        .HasColumnName("ai_draft_content");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_staff_id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("archived_at");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DraftedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("drafted_by_staff_id");

                    b.Property<DateOnly?>("IssuedDate")
                        .HasColumnType("date")
                        .HasColumnName("issued_date");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_number");

                    b.Property<Guid?>("RelatedIncomingDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_incoming_document_id");

                    b.Property<Guid?>("RelatedMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_member_id");

                    b.Property<JsonElement>("ReviewIssues")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("review_issues")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Editing")
                        .HasColumnName("status");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_outgoing_documents");

                    b.HasIndex("ApprovedByStaffId")
                        .HasDatabaseName("ix_outgoing_documents_approved_by_staff_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outgoing_documents_created_at");

                    b.HasIndex("DraftedByStaffId")
                        .HasDatabaseName("ix_outgoing_documents_drafted_by_staff_id");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_outgoing_documents_reference_number")
                        .HasFilter("reference_number IS NOT NULL");

                    b.HasIndex("RelatedIncomingDocumentId")
                        .HasDatabaseName("ix_outgoing_documents_related_incoming_document_id");

                    b.HasIndex("RelatedMemberId")
                        .HasDatabaseName("ix_outgoing_documents_related_member_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_outgoing_documents_status");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_outgoing_documents_template_id");

                    b.ToTable("outgoing_documents", null, t =>
                        {
                            t.HasCheckConstraint("ck_outgoing_documents_ai_draft_content", "status <> 'AiDraft' OR ai_draft_content IS NOT NULL");

                            t.HasCheckConstraint("ck_outgoing_documents_approved_status", "status NOT IN ('Approved', 'Archived') OR (approved_by_staff_id IS NOT NULL AND approved_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_outgoing_documents_approved_tuple", "(approved_by_staff_id IS NULL AND approved_at IS NULL) OR (approved_by_staff_id IS NOT NULL AND approved_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_outgoing_documents_archived_tuple", "(status = 'Archived' AND archived_at IS NOT NULL AND reference_number IS NOT NULL AND issued_date IS NOT NULL) OR (status <> 'Archived' AND archived_at IS NULL)");

                            t.HasCheckConstraint("ck_outgoing_documents_reference_tuple", "(reference_number IS NULL AND issued_date IS NULL) OR (reference_number IS NOT NULL AND issued_date IS NOT NULL)");

                            t.HasCheckConstraint("ck_outgoing_documents_review_issues_array", "jsonb_typeof(review_issues) = 'array'");

                            t.HasCheckConstraint("ck_outgoing_documents_status", "status IN ('AiDraft', 'Editing', 'PendingReview', 'ReviewFailed', 'PendingApproval', 'Approved', 'Archived')");
                        });
                });

            modelBuilder.Entity("DigitalOps.API.Features.Reminders.ReminderHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Unread")
                        .HasColumnName("delivery_status");

                    b.Property<Guid>("IncomingDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incoming_document_id");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("read_at");

                    b.Property<Guid>("RecipientStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_staff_id");

                    b.Property<DateOnly>("ReminderDate")
                        .HasColumnType("date")
                        .HasColumnName("reminder_date");

                    b.Property<string>("ReminderKind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("reminder_kind");

                    b.HasKey("Id")
                        .HasName("pk_reminder_history");

                    b.HasIndex("IncomingDocumentId")
                        .HasDatabaseName("ix_reminder_history_incoming_document_id");

                    b.HasIndex("RecipientStaffId", "DeliveryStatus", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_reminder_history_recipient_status");

                    b.HasIndex("IncomingDocumentId", "RecipientStaffId", "ReminderKind", "ReminderDate")
                        .IsUnique()
                        .HasDatabaseName("ux_reminder_history_idempotency");

                    b.ToTable("reminder_history", null, t =>
                        {
                            t.HasCheckConstraint("ck_reminder_history_delivery_status", "delivery_status IN ('Unread', 'Read')");

                            t.HasCheckConstraint("ck_reminder_history_kind", "reminder_kind IN ('BeforeDeadline', 'DueDate', 'Overdue')");

                            t.HasCheckConstraint("ck_reminder_history_read_at", "(delivery_status = 'Read' AND read_at IS NOT NULL) OR (delivery_status = 'Unread' AND read_at IS NULL)");
                        });
                });

            modelBuilder.Entity("DigitalOps.API.Features.Review.ReviewHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AttemptNo")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_no");

                    b.Property<string>("ContentSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_snapshot");

                    b.Property<Guid>("OutgoingDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("outgoing_document_id");

                    b.Property<JsonElement>("ReviewIssues")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("review_issues")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("ReviewResult")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("review_result");

                    b.Property<string>("ReviewSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("review_source");

                    b.Property<DateTime>("ReviewedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("reviewed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("ReviewedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_staff_id");

                    b.HasKey("Id")
                        .HasName("pk_review_history");

                    b.HasIndex("ReviewedByStaffId")
                        .HasDatabaseName("ix_review_history_reviewed_by_staff_id");

                    b.HasIndex("OutgoingDocumentId", "AttemptNo")
                        .IsUnique()
                        .HasDatabaseName("ux_review_history_document_attempt");

                    b.HasIndex("OutgoingDocumentId", "ReviewedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_review_history_document_reviewed_at");

                    b.ToTable("review_history", null, t =>
                        {
                            t.HasCheckConstraint("ck_review_history_attempt_no", "attempt_no > 0");

                            t.HasCheckConstraint("ck_review_history_issues_array", "jsonb_typeof(review_issues) = 'array'");

                            t.HasCheckConstraint("ck_review_history_result", "review_result IN ('Failed', 'Passed')");

                            t.HasCheckConstraint("ck_review_history_source", "review_source IN ('Rule', 'AI', 'Hybrid')");
                        });
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Data.Entities.RagChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("chunk_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.PrimitiveCollection<string[]>("AllowedRoles")
                        .IsRequired()
                        .HasColumnType("character varying(64)[]")
                        .HasColumnName("allowed_roles");

                    b.Property<int>("CharacterEnd")
                        .HasColumnType("integer")
                        .HasColumnName("character_end");

                    b.Property<int>("CharacterStart")
                        .HasColumnType("integer")
                        .HasColumnName("character_start");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<Guid>("ChunkSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("chunk_set_id");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("content_sha256")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.PrimitiveCollection<string[]>("DeniedRoles")
                        .IsRequired()
                        .HasColumnType("character varying(64)[]")
                        .HasColumnName("denied_roles");

                    b.Property<string>("HeadingPath")
                        .HasColumnType("text")
                        .HasColumnName("heading_path");

                    b.PrimitiveCollection<int[]>("PageNumbers")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("page_numbers");

                    b.Property<string>("SecurityClassification")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("internal")
                        .HasColumnName("security_classification");

                    b.Property<string>("StructureMetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("structure_metadata");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.HasKey("Id")
                        .HasName("pk_rag_chunks");

                    b.HasIndex("ChunkSetId", "ChunkIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_rag_chunks_set_index");

                    b.HasIndex("ChunkSetId", "ContentSha256")
                        .IsUnique()
                        .HasDatabaseName("ux_rag_chunks_set_hash");

                    b.ToTable("rag_chunks", null, t =>
                        {
                            t.HasCheckConstraint("ck_rag_chunks_offsets", "character_start >= 0 AND character_end > character_start");

                            t.HasCheckConstraint("ck_rag_chunks_token_count", "token_count > 0 AND token_count <= 512");
                        });
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Data.Entities.RagChunkSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("chunk_set_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ChunkerVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("chunker_version");

                    b.Property<string>("ChunkingStrategy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("chunking_strategy");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("integer")
                        .HasColumnName("max_tokens");

                    b.Property<int>("OverlapTokens")
                        .HasColumnType("integer")
                        .HasColumnName("overlap_tokens");

                    b.Property<int?>("SoftMaxTokens")
                        .HasColumnType("integer")
                        .HasColumnName("soft_max_tokens");

                    b.Property<int>("TargetTokens")
                        .HasColumnType("integer")
                        .HasColumnName("target_tokens");

                    b.Property<string>("TokenizerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tokenizer_name");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("integer")
                        .HasColumnName("total_chunks");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.HasKey("Id")
                        .HasName("pk_rag_chunk_sets");

                    b.HasIndex("VersionId")
                        .IsUnique()
                        .HasDatabaseName("ux_rag_chunk_sets_version_id");

                    b.ToTable("rag_chunk_sets", null, t =>
                        {
                            t.HasCheckConstraint("ck_rag_chunk_sets_limits", "target_tokens > 0 AND overlap_tokens >= 0 AND overlap_tokens < target_tokens AND (soft_max_tokens IS NULL OR (soft_max_tokens >= target_tokens AND soft_max_tokens <= 512)) AND (max_tokens IS NULL OR (max_tokens >= COALESCE(soft_max_tokens, target_tokens) AND max_tokens <= 512)) AND total_chunks > 0");
                        });
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Data.Entities.RagCitationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BusinessEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_entity_id");

                    b.Property<string>("BusinessEntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("business_entity_type");

                    b.Property<string>("CitationPayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("citation_payload");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_text");

                    b.PrimitiveCollection<Guid[]>("RetrievedChunkIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("retrieved_chunk_ids");

                    b.HasKey("Id")
                        .HasName("pk_rag_citation_snapshots");

                    b.ToTable("rag_citation_snapshots", (string)null);
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Data.Entities.RagDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("document_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ActiveChunkSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_chunk_set_id");

                    b.Property<Guid?>("ActiveVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_version_id");

                    b.Property<string>("AuthorityNamespace")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("authority_namespace");

                    b.Property<string>("CanonicalDocumentKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("canonical_document_key");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DocumentIdentityStrategy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("document_identity_strategy");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_rag_documents");

                    b.HasIndex("ActiveChunkSetId")
                        .HasDatabaseName("ix_rag_documents_active_chunk_set_id");

                    b.HasIndex("ActiveVersionId")
                        .HasDatabaseName("ix_rag_documents_active_version_id");

                    b.HasIndex("CanonicalDocumentKey")
                        .IsUnique()
                        .HasDatabaseName("idx_rag_docs_canonical_key");

                    b.ToTable("rag_documents", (string)null);
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Data.Entities.RagDocumentSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("source_mapping_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AdmissionApprovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("admission_approved_at");

                    b.Property<string>("AdmissionApprovedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("admission_approved_by");

                    b.Property<string>("AdmissionReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("admission_reference");

                    b.Property<string>("CorpusType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("general")
                        .HasColumnName("corpus_type");

                    b.Property<DateTime>("CrawledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("crawled_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("PublishPolicy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("blocked")
                        .HasColumnName("publish_policy");

                    b.Property<string>("RegistryEntryId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("registry_entry_id");

                    b.Property<string>("RegistryVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("registry_version");

                    b.Property<string>("SourceDocumentUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("source_document_url");

                    b.Property<string>("SourceDomain")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("source_domain");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceNamespace")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_namespace");

                    b.Property<string>("SourceTrustTier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("unverified")
                        .HasColumnName("source_trust_tier");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.HasKey("Id")
                        .HasName("pk_rag_document_sources");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_rag_document_sources_document_id");

                    b.HasIndex("CorpusType", "SourceTrustTier")
                        .HasDatabaseName("idx_rag_doc_sources_corpus_trust");

                    b.HasIndex("VersionId", "SourceId", "SourceDocumentUrl")
                        .IsUnique()
                        .HasDatabaseName("ux_rag_doc_sources_version_source_url");

                    b.ToTable("rag_document_sources", null, t =>
                        {
                            t.HasCheckConstraint("ck_rag_document_sources_corpus", "corpus_type IN ('general', 'legal_reference')");

                            t.HasCheckConstraint("ck_rag_document_sources_publish_policy", "publish_policy IN ('authoritative', 'verified_copy', 'cross_check_only', 'blocked')");

                            t.HasCheckConstraint("ck_rag_document_sources_trust", "source_trust_tier IN ('official', 'verified_copy', 'aggregator', 'unverified')");

                            t.HasCheckConstraint("ck_rag_document_sources_trust_policy_pair", "(source_trust_tier = 'official' AND publish_policy = 'authoritative') OR (source_trust_tier = 'verified_copy' AND publish_policy = 'verified_copy') OR (source_trust_tier = 'aggregator' AND publish_policy = 'cross_check_only') OR (source_trust_tier = 'unverified' AND publish_policy = 'blocked')");
                        });
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Data.Entities.RagDocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("version_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CharCount")
                        .HasColumnType("integer")
                        .HasColumnName("char_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("document_number");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("document_type");

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<string>("ExtractionQualityJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extraction_quality");

                    b.Property<DateOnly?>("IssuedDate")
                        .HasColumnType("date")
                        .HasColumnName("issued_date");

                    b.Property<string>("Issuer")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("issuer");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("language");

                    b.Property<string>("LegalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("status_unknown")
                        .HasColumnName("legal_status");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("metadata");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("mime_type");

                    b.Property<string>("NormalizedTextSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("normalized_text_sha256")
                        .IsFixedLength();

                    b.Property<string>("NormalizedTextUri")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("normalized_text_uri");

                    b.Property<string>("RawArtifactUri")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("raw_artifact_uri");

                    b.Property<string>("RawSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("raw_sha256")
                        .IsFixedLength();

                    b.Property<string>("SourceVersion")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_version");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer")
                        .HasColumnName("word_count");

                    b.HasKey("Id")
                        .HasName("pk_rag_document_versions");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("idx_rag_doc_versions_doc_id");

                    b.HasIndex("DocumentId", "NormalizedTextSha256")
                        .IsUnique()
                        .HasDatabaseName("ux_rag_doc_versions_document_hash");

                    b.ToTable("rag_document_versions", null, t =>
                        {
                            t.HasCheckConstraint("ck_rag_document_versions_effectivity", "effective_from IS NULL OR effective_to IS NULL OR effective_from <= effective_to");

                            t.HasCheckConstraint("ck_rag_document_versions_legal_status", "legal_status IN ('current', 'expired', 'repealed', 'superseded', 'status_unknown')");
                        });
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Data.Entities.RagIndexGeneration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("index_generation_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("activated_at");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("collection_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DistanceMetric")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("distance_metric");

                    b.Property<int>("EmbeddingDimension")
                        .HasColumnType("integer")
                        .HasColumnName("embedding_dimension");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("embedding_model");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_rag_index_generations");

                    b.ToTable("rag_index_generations", null, t =>
                        {
                            t.HasCheckConstraint("ck_rag_index_generations_status", "status IN ('building', 'active', 'retired', 'failed')");
                        });
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Data.Entities.RagIndexPoint", b =>
                {
                    b.Property<Guid>("PointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("point_id");

                    b.Property<Guid>("ChunkId")
                        .HasColumnType("uuid")
                        .HasColumnName("chunk_id");

                    b.Property<Guid>("ChunkSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("chunk_set_id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid>("IndexGenerationId")
                        .HasColumnType("uuid")
                        .HasColumnName("index_generation_id");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("indexed_at");

                    b.Property<Guid>("QdrantPointId")
                        .HasColumnType("uuid")
                        .HasColumnName("qdrant_point_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.HasKey("PointId")
                        .HasName("pk_rag_index_points");

                    b.HasIndex("ChunkId")
                        .HasDatabaseName("ix_rag_index_points_chunk_id");

                    b.HasIndex("QdrantPointId")
                        .IsUnique()
                        .HasDatabaseName("ix_rag_index_points_qdrant_point_id");

                    b.HasIndex("IndexGenerationId", "ChunkId")
                        .IsUnique()
                        .HasDatabaseName("ux_rag_index_points_generation_chunk");

                    b.ToTable("rag_index_points", null, t =>
                        {
                            t.HasCheckConstraint("ck_rag_index_points_status", "status IN ('pending', 'indexed', 'failed', 'deleted')");
                        });
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Data.Entities.RagIngestionError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("error_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EntityId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("job_id");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("stack_trace");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("stage");

                    b.HasKey("Id")
                        .HasName("pk_rag_ingestion_errors");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_rag_ingestion_errors_job_id");

                    b.ToTable("rag_ingestion_errors", (string)null);
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Data.Entities.RagIngestionJob", b =>
                {
                    b.Property<string>("JobId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("job_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("text")
                        .HasColumnName("error_summary");

                    b.Property<int>("FailedObservations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_observations");

                    b.Property<int>("ProcessedObservations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("processed_observations");

                    b.Property<string>("StagingDirectory")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("staging_directory");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("TotalObservations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_observations");

                    b.HasKey("JobId")
                        .HasName("pk_rag_ingestion_jobs");

                    b.ToTable("rag_ingestion_jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_rag_ingestion_jobs_status", "status IN ('running', 'completed', 'failed')");
                        });
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Identity.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_user_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("position");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_staff");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_staff_email");

                    b.HasIndex("IdentityUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_staff_identity_user_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_staff_is_active");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("DigitalOps.API.Features.Attachments.Attachment", b =>
                {
                    b.HasOne("DigitalOps.API.Features.IncomingDocuments.IncomingDocument", "IncomingDocument")
                        .WithMany("Attachments")
                        .HasForeignKey("IncomingDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_attachments_incoming_documents_incoming_document_id");

                    b.HasOne("DigitalOps.API.Features.OutgoingDocuments.OutgoingDocument", "OutgoingDocument")
                        .WithMany("Attachments")
                        .HasForeignKey("OutgoingDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_attachments_outgoing_documents_outgoing_document_id");

                    b.HasOne("DigitalOps.API.Shared.Identity.Staff", "UploadedByStaff")
                        .WithMany()
                        .HasForeignKey("UploadedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_staff_uploaded_by_staff_id");

                    b.Navigation("IncomingDocument");

                    b.Navigation("OutgoingDocument");

                    b.Navigation("UploadedByStaff");
                });

            modelBuilder.Entity("DigitalOps.API.Features.Drafting.DocumentTemplate", b =>
                {
                    b.HasOne("DigitalOps.API.Features.Drafting.DocumentType", "DocumentType")
                        .WithMany("Templates")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_document_templates_document_types_document_type_id");

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("DigitalOps.API.Features.IncomingDocuments.IncomingDocument", b =>
                {
                    b.HasOne("DigitalOps.API.Shared.Identity.Staff", "AssignedToStaff")
                        .WithMany()
                        .HasForeignKey("AssignedToStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_incoming_documents_staff_assigned_to_staff_id");

                    b.HasOne("DigitalOps.API.Shared.Identity.Staff", "AssignmentConfirmedByStaff")
                        .WithMany()
                        .HasForeignKey("AssignmentConfirmedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_incoming_documents_staff_assignment_confirmed_by_staff_id");

                    b.HasOne("DigitalOps.API.Features.Drafting.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incoming_documents_document_types_document_type_id");

                    b.HasOne("DigitalOps.API.Shared.Identity.Staff", "SuggestedStaff")
                        .WithMany()
                        .HasForeignKey("SuggestedStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_incoming_documents_staff_suggested_staff_id");

                    b.Navigation("AssignedToStaff");

                    b.Navigation("AssignmentConfirmedByStaff");

                    b.Navigation("DocumentType");

                    b.Navigation("SuggestedStaff");
                });

            modelBuilder.Entity("DigitalOps.API.Features.OutgoingDocuments.OutgoingDocument", b =>
                {
                    b.HasOne("DigitalOps.API.Shared.Identity.Staff", "ApprovedByStaff")
                        .WithMany()
                        .HasForeignKey("ApprovedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_outgoing_documents_staff_approved_by_staff_id");

                    b.HasOne("DigitalOps.API.Shared.Identity.Staff", "DraftedByStaff")
                        .WithMany()
                        .HasForeignKey("DraftedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_outgoing_documents_staff_drafted_by_staff_id");

                    b.HasOne("DigitalOps.API.Features.IncomingDocuments.IncomingDocument", "RelatedIncomingDocument")
                        .WithMany()
                        .HasForeignKey("RelatedIncomingDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_outgoing_documents_incoming_documents_related_incoming_docu");

                    b.HasOne("DigitalOps.API.Features.Members.Member", "RelatedMember")
                        .WithMany()
                        .HasForeignKey("RelatedMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_outgoing_documents_members_related_member_id");

                    b.HasOne("DigitalOps.API.Features.Drafting.DocumentTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_outgoing_documents_document_templates_template_id");

                    b.Navigation("ApprovedByStaff");

                    b.Navigation("DraftedByStaff");

                    b.Navigation("RelatedIncomingDocument");

                    b.Navigation("RelatedMember");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DigitalOps.API.Features.Reminders.ReminderHistory", b =>
                {
                    b.HasOne("DigitalOps.API.Features.IncomingDocuments.IncomingDocument", "IncomingDocument")
                        .WithMany()
                        .HasForeignKey("IncomingDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reminder_history_incoming_documents_incoming_document_id");

                    b.HasOne("DigitalOps.API.Shared.Identity.Staff", "RecipientStaff")
                        .WithMany()
                        .HasForeignKey("RecipientStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reminder_history_staff_recipient_staff_id");

                    b.Navigation("IncomingDocument");

                    b.Navigation("RecipientStaff");
                });

            modelBuilder.Entity("DigitalOps.API.Features.Review.ReviewHistory", b =>
                {
                    b.HasOne("DigitalOps.API.Features.OutgoingDocuments.OutgoingDocument", "OutgoingDocument")
                        .WithMany("ReviewHistory")
                        .HasForeignKey("OutgoingDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_review_history_outgoing_documents_outgoing_document_id");

                    b.HasOne("DigitalOps.API.Shared.Identity.Staff", "ReviewedByStaff")
                        .WithMany()
                        .HasForeignKey("ReviewedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_review_history_staff_reviewed_by_staff_id");

                    b.Navigation("OutgoingDocument");

                    b.Navigation("ReviewedByStaff");
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Data.Entities.RagChunk", b =>
                {
                    b.HasOne("DigitalOps.API.Shared.Data.Entities.RagChunkSet", "ChunkSet")
                        .WithMany()
                        .HasForeignKey("ChunkSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rag_chunks_rag_chunk_sets_chunk_set_id");

                    b.Navigation("ChunkSet");
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Data.Entities.RagChunkSet", b =>
                {
                    b.HasOne("DigitalOps.API.Shared.Data.Entities.RagDocumentVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rag_chunk_sets_rag_document_versions_version_id");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Data.Entities.RagDocument", b =>
                {
                    b.HasOne("DigitalOps.API.Shared.Data.Entities.RagChunkSet", "ActiveChunkSet")
                        .WithMany()
                        .HasForeignKey("ActiveChunkSetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_rag_documents_rag_chunk_sets_active_chunk_set_id");

                    b.HasOne("DigitalOps.API.Shared.Data.Entities.RagDocumentVersion", "ActiveVersion")
                        .WithMany()
                        .HasForeignKey("ActiveVersionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_rag_documents_rag_document_versions_active_version_id");

                    b.Navigation("ActiveChunkSet");

                    b.Navigation("ActiveVersion");
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Data.Entities.RagDocumentSource", b =>
                {
                    b.HasOne("DigitalOps.API.Shared.Data.Entities.RagDocument", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rag_document_sources_rag_documents_document_id");

                    b.HasOne("DigitalOps.API.Shared.Data.Entities.RagDocumentVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rag_document_sources_rag_document_versions_version_id");

                    b.Navigation("Document");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Data.Entities.RagDocumentVersion", b =>
                {
                    b.HasOne("DigitalOps.API.Shared.Data.Entities.RagDocument", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rag_document_versions_rag_documents_document_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Data.Entities.RagIndexPoint", b =>
                {
                    b.HasOne("DigitalOps.API.Shared.Data.Entities.RagChunk", "Chunk")
                        .WithMany()
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rag_index_points_rag_chunks_chunk_id");

                    b.HasOne("DigitalOps.API.Shared.Data.Entities.RagIndexGeneration", "IndexGeneration")
                        .WithMany()
                        .HasForeignKey("IndexGenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rag_index_points_rag_index_generations_index_generation_id");

                    b.Navigation("Chunk");

                    b.Navigation("IndexGeneration");
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Data.Entities.RagIngestionError", b =>
                {
                    b.HasOne("DigitalOps.API.Shared.Data.Entities.RagIngestionJob", "IngestionJob")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rag_ingestion_errors_rag_ingestion_jobs_job_id");

                    b.Navigation("IngestionJob");
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Identity.Staff", b =>
                {
                    b.HasOne("DigitalOps.API.Shared.Identity.ApplicationUser", "IdentityUser")
                        .WithOne("Staff")
                        .HasForeignKey("DigitalOps.API.Shared.Identity.Staff", "IdentityUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_users_identity_user_id");

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DigitalOps.API.Shared.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DigitalOps.API.Shared.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("DigitalOps.API.Shared.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DigitalOps.API.Shared.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("DigitalOps.API.Features.Drafting.DocumentType", b =>
                {
                    b.Navigation("Templates");
                });

            modelBuilder.Entity("DigitalOps.API.Features.IncomingDocuments.IncomingDocument", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("DigitalOps.API.Features.OutgoingDocuments.OutgoingDocument", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("ReviewHistory");
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
