// <auto-generated />
using System;
using System.Text.Json;
using DigitalOps.API.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DigitalOps.API.Shared.Data.Migrations
{
    [DbContext(typeof(DigitalOpsDbContext))]
    [Migration("20260801071123_AddOutgoingDocuments")]
    partial class AddOutgoingDocuments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DigitalOps.API.Features.Attachments.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ExtractedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("extracted_at");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text")
                        .HasColumnName("extracted_text");

                    b.Property<string>("ExtractionError")
                        .HasColumnType("text")
                        .HasColumnName("extraction_error");

                    b.Property<string>("ExtractionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("extraction_status");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<Guid?>("IncomingDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incoming_document_id");

                    b.Property<Guid?>("OutgoingDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("outgoing_document_id");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("file_url");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UploadedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_staff_id");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("ExtractionStatus")
                        .HasDatabaseName("ix_attachments_extraction_status");

                    b.HasIndex("IncomingDocumentId")
                        .HasDatabaseName("ix_attachments_incoming_document_id");

                    b.HasIndex("OutgoingDocumentId")
                        .HasDatabaseName("ix_attachments_outgoing_document_id");

                    b.HasIndex("UploadedByStaffId")
                        .HasDatabaseName("ix_attachments_uploaded_by_staff_id");

                    b.ToTable("attachments", null, t =>
                        {
                            t.HasCheckConstraint("ck_attachments_exactly_one_parent", "num_nonnulls(incoming_document_id, outgoing_document_id) = 1");

                            t.HasCheckConstraint("ck_attachments_extraction_status", "extraction_status IN ('Pending', 'Processing', 'Succeeded', 'Failed', 'Unsupported')");

                            t.HasCheckConstraint("ck_attachments_failed_error", "extraction_status <> 'Failed' OR (extraction_error IS NOT NULL AND length(trim(extraction_error)) > 0)");

                            t.HasCheckConstraint("ck_attachments_succeeded_extracted_at", "extraction_status <> 'Succeeded' OR extracted_at IS NOT NULL");
                        });
                });

            modelBuilder.Entity("DigitalOps.API.Features.Drafting.DocumentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_type_id");

                    b.Property<JsonElement>("FormatRules")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("format_rules")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TemplateContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_content");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_document_templates");

                    b.HasIndex("DocumentTypeId")
                        .HasDatabaseName("ix_document_templates_document_type_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_document_templates_is_active");

                    b.HasIndex("DocumentTypeId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_document_templates_type_name");

                    b.ToTable("document_templates", null, t =>
                        {
                            t.HasCheckConstraint("ck_document_templates_format_rules_object", "jsonb_typeof(format_rules) = 'object'");
                        });
                });

            modelBuilder.Entity("DigitalOps.API.Features.Drafting.DocumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_document_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_document_types_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_document_types_is_active");

                    b.ToTable("document_types", (string)null);
                });

            modelBuilder.Entity("DigitalOps.API.Features.IncomingDocuments.IncomingDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AssignedToStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_staff_id");

                    b.Property<decimal?>("AssignmentConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("assignment_confidence");

                    b.Property<DateTime?>("AssignmentConfirmedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("assignment_confirmed_at");

                    b.Property<Guid?>("AssignmentConfirmedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_confirmed_by_staff_id");

                    b.Property<DateTime?>("AssignmentSuggestedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("assignment_suggested_at");

                    b.Property<string>("AssignmentSuggestionReason")
                        .HasColumnType("text")
                        .HasColumnName("assignment_suggestion_reason");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_type_id");

                    b.Property<DateOnly>("ReceivedDate")
                        .HasColumnType("date")
                        .HasColumnName("received_date");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_number");

                    b.Property<string>("SenderOrg")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sender_org");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("New")
                        .HasColumnName("status");

                    b.Property<Guid?>("SuggestedStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggested_staff_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_incoming_documents");

                    b.HasIndex("AssignmentConfirmedByStaffId")
                        .HasDatabaseName("ix_incoming_documents_confirmed_by_staff_id");

                    b.HasIndex("DocumentTypeId")
                        .HasDatabaseName("ix_incoming_documents_document_type_id");

                    b.HasIndex("SuggestedStaffId")
                        .HasDatabaseName("ix_incoming_documents_suggested_staff_id");

                    b.HasIndex("AssignedToStaffId", "Status")
                        .HasDatabaseName("ix_incoming_documents_assigned_status");

                    b.HasIndex("ReferenceNumber", "SenderOrg")
                        .HasDatabaseName("ix_incoming_documents_reference_sender");

                    b.HasIndex("Status", "Deadline")
                        .HasDatabaseName("ix_incoming_documents_status_deadline");

                    b.ToTable("incoming_documents", null, t =>
                        {
                            t.HasCheckConstraint("ck_incoming_documents_assignment_confidence", "assignment_confidence IS NULL OR (assignment_confidence >= 0 AND assignment_confidence <= 1)");

                            t.HasCheckConstraint("ck_incoming_documents_assignment_tuple", "(assigned_to_staff_id IS NULL AND assignment_confirmed_by_staff_id IS NULL AND assignment_confirmed_at IS NULL) OR (assigned_to_staff_id IS NOT NULL AND assignment_confirmed_by_staff_id IS NOT NULL AND assignment_confirmed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_incoming_documents_received_deadline", "received_date <= deadline");

                            t.HasCheckConstraint("ck_incoming_documents_status", "status IN ('New', 'InProgress', 'Completed', 'Overdue')");

                            t.HasCheckConstraint("ck_incoming_documents_status_completed_at", "(status = 'Completed' AND completed_at IS NOT NULL) OR (status <> 'Completed' AND completed_at IS NULL)");

                            t.HasCheckConstraint("ck_incoming_documents_suggestion_tuple", "(suggested_staff_id IS NULL AND assignment_suggestion_reason IS NULL AND assignment_confidence IS NULL AND assignment_suggested_at IS NULL) OR (suggested_staff_id IS NOT NULL AND assignment_suggested_at IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("DigitalOps.API.Features.Members.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<DateOnly?>("JoinDate")
                        .HasColumnType("date")
                        .HasColumnName("join_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("position");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_members_email");

                    b.HasIndex("FullName")
                        .HasDatabaseName("ix_members_full_name");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_members_phone");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_members_status");

                    b.ToTable("members", null, t =>
                        {
                            t.HasCheckConstraint("ck_members_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("DigitalOps.API.Features.OutgoingDocuments.OutgoingDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AiDraftContent")
                        .HasColumnType("text")
                        .HasColumnName("ai_draft_content");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_staff_id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("archived_at");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DraftedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("drafted_by_staff_id");

                    b.Property<DateOnly?>("IssuedDate")
                        .HasColumnType("date")
                        .HasColumnName("issued_date");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_number");

                    b.Property<Guid?>("RelatedIncomingDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_incoming_document_id");

                    b.Property<Guid?>("RelatedMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_member_id");

                    b.Property<JsonElement>("ReviewIssues")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("review_issues")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Editing")
                        .HasColumnName("status");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_outgoing_documents");

                    b.HasIndex("ApprovedByStaffId")
                        .HasDatabaseName("ix_outgoing_documents_approved_by_staff_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outgoing_documents_created_at");

                    b.HasIndex("DraftedByStaffId")
                        .HasDatabaseName("ix_outgoing_documents_drafted_by_staff_id");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_outgoing_documents_reference_number")
                        .HasFilter("reference_number IS NOT NULL");

                    b.HasIndex("RelatedIncomingDocumentId")
                        .HasDatabaseName("ix_outgoing_documents_related_incoming_document_id");

                    b.HasIndex("RelatedMemberId")
                        .HasDatabaseName("ix_outgoing_documents_related_member_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_outgoing_documents_status");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_outgoing_documents_template_id");

                    b.ToTable("outgoing_documents", null, t =>
                        {
                            t.HasCheckConstraint("ck_outgoing_documents_ai_draft_content", "status <> 'AiDraft' OR ai_draft_content IS NOT NULL");

                            t.HasCheckConstraint("ck_outgoing_documents_approved_status", "status NOT IN ('Approved', 'Archived') OR (approved_by_staff_id IS NOT NULL AND approved_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_outgoing_documents_approved_tuple", "(approved_by_staff_id IS NULL AND approved_at IS NULL) OR (approved_by_staff_id IS NOT NULL AND approved_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_outgoing_documents_archived_tuple", "(status = 'Archived' AND archived_at IS NOT NULL AND reference_number IS NOT NULL AND issued_date IS NOT NULL) OR (status <> 'Archived' AND archived_at IS NULL)");

                            t.HasCheckConstraint("ck_outgoing_documents_reference_tuple", "(reference_number IS NULL AND issued_date IS NULL) OR (reference_number IS NOT NULL AND issued_date IS NOT NULL)");

                            t.HasCheckConstraint("ck_outgoing_documents_review_issues_array", "jsonb_typeof(review_issues) = 'array'");

                            t.HasCheckConstraint("ck_outgoing_documents_status", "status IN ('AiDraft', 'Editing', 'PendingReview', 'ReviewFailed', 'PendingApproval', 'Approved', 'Archived')");
                        });
                });

            modelBuilder.Entity("DigitalOps.API.Features.Reminders.ReminderHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Unread")
                        .HasColumnName("delivery_status");

                    b.Property<Guid>("IncomingDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incoming_document_id");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("read_at");

                    b.Property<Guid>("RecipientStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_staff_id");

                    b.Property<DateOnly>("ReminderDate")
                        .HasColumnType("date")
                        .HasColumnName("reminder_date");

                    b.Property<string>("ReminderKind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("reminder_kind");

                    b.HasKey("Id")
                        .HasName("pk_reminder_history");

                    b.HasIndex("IncomingDocumentId")
                        .HasDatabaseName("ix_reminder_history_incoming_document_id");

                    b.HasIndex("RecipientStaffId", "DeliveryStatus", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_reminder_history_recipient_status");

                    b.HasIndex("IncomingDocumentId", "RecipientStaffId", "ReminderKind", "ReminderDate")
                        .IsUnique()
                        .HasDatabaseName("ux_reminder_history_idempotency");

                    b.ToTable("reminder_history", null, t =>
                        {
                            t.HasCheckConstraint("ck_reminder_history_delivery_status", "delivery_status IN ('Unread', 'Read')");

                            t.HasCheckConstraint("ck_reminder_history_kind", "reminder_kind IN ('BeforeDeadline', 'DueDate', 'Overdue')");

                            t.HasCheckConstraint("ck_reminder_history_read_at", "(delivery_status = 'Read' AND read_at IS NOT NULL) OR (delivery_status = 'Unread' AND read_at IS NULL)");
                        });
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Identity.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_user_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("position");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_staff");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_staff_email");

                    b.HasIndex("IdentityUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_staff_identity_user_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_staff_is_active");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("DigitalOps.API.Features.Attachments.Attachment", b =>
                {
                    b.HasOne("DigitalOps.API.Features.IncomingDocuments.IncomingDocument", "IncomingDocument")
                        .WithMany("Attachments")
                        .HasForeignKey("IncomingDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_attachments_incoming_documents_incoming_document_id");

                    b.HasOne("DigitalOps.API.Features.OutgoingDocuments.OutgoingDocument", "OutgoingDocument")
                        .WithMany("Attachments")
                        .HasForeignKey("OutgoingDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_attachments_outgoing_documents_outgoing_document_id");

                    b.HasOne("DigitalOps.API.Shared.Identity.Staff", "UploadedByStaff")
                        .WithMany()
                        .HasForeignKey("UploadedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_staff_uploaded_by_staff_id");

                    b.Navigation("IncomingDocument");

                    b.Navigation("OutgoingDocument");

                    b.Navigation("UploadedByStaff");
                });

            modelBuilder.Entity("DigitalOps.API.Features.Drafting.DocumentTemplate", b =>
                {
                    b.HasOne("DigitalOps.API.Features.Drafting.DocumentType", "DocumentType")
                        .WithMany("Templates")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_document_templates_document_types_document_type_id");

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("DigitalOps.API.Features.IncomingDocuments.IncomingDocument", b =>
                {
                    b.HasOne("DigitalOps.API.Shared.Identity.Staff", "AssignedToStaff")
                        .WithMany()
                        .HasForeignKey("AssignedToStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_incoming_documents_staff_assigned_to_staff_id");

                    b.HasOne("DigitalOps.API.Shared.Identity.Staff", "AssignmentConfirmedByStaff")
                        .WithMany()
                        .HasForeignKey("AssignmentConfirmedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_incoming_documents_staff_assignment_confirmed_by_staff_id");

                    b.HasOne("DigitalOps.API.Features.Drafting.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incoming_documents_document_types_document_type_id");

                    b.HasOne("DigitalOps.API.Shared.Identity.Staff", "SuggestedStaff")
                        .WithMany()
                        .HasForeignKey("SuggestedStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_incoming_documents_staff_suggested_staff_id");

                    b.Navigation("AssignedToStaff");

                    b.Navigation("AssignmentConfirmedByStaff");

                    b.Navigation("DocumentType");

                    b.Navigation("SuggestedStaff");
                });

            modelBuilder.Entity("DigitalOps.API.Features.OutgoingDocuments.OutgoingDocument", b =>
                {
                    b.HasOne("DigitalOps.API.Shared.Identity.Staff", "ApprovedByStaff")
                        .WithMany()
                        .HasForeignKey("ApprovedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_outgoing_documents_staff_approved_by_staff_id");

                    b.HasOne("DigitalOps.API.Shared.Identity.Staff", "DraftedByStaff")
                        .WithMany()
                        .HasForeignKey("DraftedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_outgoing_documents_staff_drafted_by_staff_id");

                    b.HasOne("DigitalOps.API.Features.IncomingDocuments.IncomingDocument", "RelatedIncomingDocument")
                        .WithMany()
                        .HasForeignKey("RelatedIncomingDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_outgoing_documents_incoming_documents_related_incoming_docu");

                    b.HasOne("DigitalOps.API.Features.Members.Member", "RelatedMember")
                        .WithMany()
                        .HasForeignKey("RelatedMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_outgoing_documents_members_related_member_id");

                    b.HasOne("DigitalOps.API.Features.Drafting.DocumentTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_outgoing_documents_document_templates_template_id");

                    b.Navigation("ApprovedByStaff");

                    b.Navigation("DraftedByStaff");

                    b.Navigation("RelatedIncomingDocument");

                    b.Navigation("RelatedMember");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DigitalOps.API.Features.Reminders.ReminderHistory", b =>
                {
                    b.HasOne("DigitalOps.API.Features.IncomingDocuments.IncomingDocument", "IncomingDocument")
                        .WithMany()
                        .HasForeignKey("IncomingDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reminder_history_incoming_documents_incoming_document_id");

                    b.HasOne("DigitalOps.API.Shared.Identity.Staff", "RecipientStaff")
                        .WithMany()
                        .HasForeignKey("RecipientStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reminder_history_staff_recipient_staff_id");

                    b.Navigation("IncomingDocument");

                    b.Navigation("RecipientStaff");
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Identity.Staff", b =>
                {
                    b.HasOne("DigitalOps.API.Shared.Identity.ApplicationUser", "IdentityUser")
                        .WithOne("Staff")
                        .HasForeignKey("DigitalOps.API.Shared.Identity.Staff", "IdentityUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_users_identity_user_id");

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DigitalOps.API.Shared.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DigitalOps.API.Shared.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("DigitalOps.API.Shared.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DigitalOps.API.Shared.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("DigitalOps.API.Features.Drafting.DocumentType", b =>
                {
                    b.Navigation("Templates");
                });

            modelBuilder.Entity("DigitalOps.API.Features.IncomingDocuments.IncomingDocument", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("DigitalOps.API.Features.OutgoingDocuments.OutgoingDocument", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("DigitalOps.API.Shared.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
